description: "A modern alternative to ls"
label: "eza"
name: "eza"
repository: "extra"
repository_url: "https://archlinux.org/packages/extra/x86_64/eza/"
source_url: "https://github.com/eza-community/eza/"
url: "https://eza.rocks/"
