repos:
  - repo: local
    hooks:
      - id: generate-bash-aliases-help
        name: Generate bash aliases help file
        entry: python ./scripts/generate_bash_aliases_help.py
        language: system
      - id: process-packages
        name: Generate package lists
        entry: ./scripts/generate_package_lists.sh
        language: system
      - id: render-readme
        name: Generate README.md file
        entry: node ./templates/readme/generate-readme.js
        language: system
