repos:
  - repo: local
    hooks:
      - id: generate-bash-aliases-help
        name: Generate bash aliases help
        entry: python generate_bash_aliases_help.py
        language: system
      - id: render-readme
        name: Render README.md
        entry: node ./readme/render-readme.js
        language: system
