description: "A command-line fuzzy finder"
label: "fzf"
name: "fzf"
repository: "extra"
repository_url: "https://archlinux.org/packages/extra/x86_64/fzf/"
source_url: "https://github.com/junegunn/fzf/"
url: "https://junegunn.github.io/fzf/"
