description: "Open-source Vulkan driver for AMD GPUs - 32-bit"
label: "Vulkan driver for AMD GPUs (32-bit)"
name: "lib32-vulkan-radeon"
repository: "multilib"
repository_url: "https://archlinux.org/packages/multilib/x86_64/lib32-vulkan-radeon/"
source_url: "https://gitlab.archlinux.org/archlinux/packaging/packages/lib32-mesa/"
url: "https://www.mesa3d.org/"
