description: "Solaar is a Linux manager for many Logitech keyboards, mice, and trackpads that connect wirelessly to a USB Unifying, Bolt, Lightspeed, or Nano receiver"
label: "Solaar"
name: "solaar"
repository: "extra"
repository_url: "https://archlinux.org/packages/extra/x86_64/solaar/"
source_url: "https://github.com/pwr-Solaar/Solaar/"
url: "https://pwr-solaar.github.io/Solaar/"
