description: "A free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency"
label: "git"
name: "git"
repository: "extra"
repository_url: "https://archlinux.org/packages/extra/x86_64/git/"
source_url: "https://github.com/git/git/"
url: "https://git-scm.com/"
