"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

[character]
success_symbol = "[[󰄛](green) ❯](peach)"
error_symbol = "[[󰄛](red) ❯](peach)"
vimcmd_symbol = "[󰄛 ❮](subtext1)"

[git_branch]
style = "bold mauve"

[directory]
truncation_length = 4
style = "bold lavender"
