description: "Simple terminal UI for git commands"
label: "lazygit"
name: "lazygit"
repository: "extra"
repository_url: "https://archlinux.org/packages/extra/x86_64/lazygit/"
source_url: "https://github.com/jesseduffield/lazygit/"
url: "https://github.com/jesseduffield/lazygit/"
