description: "A modern replacement for ps written in Rust"
label: "procs"
name: "procs"
repository: "extra"
repository_url: "https://archlinux.org/packages/extra/x86_64/procs/"
source_url: "https://github.com/dalance/procs/"
url: null
