description: "Okular is a universal document viewer developed by KDE. Okular works on multiple platforms, including but not limited to Linux, Windows, Mac OS X, *BSD, etc."
label: "Okular"
name: "okular"
repository: "extra"
repository_url: "https://archlinux.org/packages/extra/x86_64/okular/"
source_url: "https://gitlab.archlinux.org/archlinux/packaging/packages/okular/"
url: "https://apps.kde.org/okular/"
