description: "The Free & Open Source Image Editor"
label: "Gimp"
name: "gimp"
repository: "extra"
repository_url: "https://archlinux.org/packages/extra/x86_64/gimp/"
source_url: "https://github.com/GNOME/gimp/"
url: "https://www.gimp.org/"
