description: "QML based X11 and Wayland display manager"
label: "SDDM"
name: "sddm"
repository: "extra"
repository_url: "https://archlinux.org/packages/extra/x86_64/sddm/"
source_url: "https://github.com/sddm/sddm/"
url: null
