name: "Base"
theme: "mocha-mauve"
packages:
  - atuin:
      install: true
      priority: "normal"
      themes: true
  - bandwhich:
      install: true
      priority: "normal"
  - base-devel:
      install: true
      priority: "highest"
  - bash:
      install: true
      priority: "high"
      secrets: true
  - bash-completion:
      install: true
      priority: "normal"
  - bash-language-server:
      install: true
      priority: "normal"
  - bat:
      install: true
      priority: "normal"
      themes: true
  - bind:
      install: true
      priority: "normal"
  - bitwarden:
      install: true
      priority: "normal"
  - bitwarden-cli:
      install: true
      priority: "normal"
  - blesh-git:
      install: true
      priority: "normal"
  - brave-bin:
      install: true
      priority: "normal"
  - broot:
      install: true
      priority: "normal"
      themes: true
  - btop:
      install: true
      priority: "normal"
      themes: true
  - btrfs-progs:
      install: true
      priority: "normal"
  - cups:
      install: true
      priority: "normal"
  - dbus:
      install: true
      priority: "normal"
  - direnv:
      install: true
      priority: "normal"
  - dive:
      install: true
      priority: "normal"
  - dkms:
      install: true
      priority: "high"
  - docker:
      install: true
      priority: "normal"
  - docker-buildx:
      install: true
      priority: "normal"
  - docker-compose:
      install: true
      priority: "normal"
  - downgrade:
      install: true
      priority: "normal"
  - expac:
      install: true
      priority: "normal"
  - eza:
      install: true
      priority: "normal"
      themes: true
  - fastfetch:
      install: true
      priority: "normal"
  - fd:
      install: true
      priority: "normal"
  - filezilla:
      install: true
      priority: "normal"
      secrets: true
  - firefox:
      install: true
      priority: "normal"
  - fzf:
      install: true
      priority: "normal"
      themes: true
  - git:
      install: true
      priority: "highest"
  - gita:
      install: true
      priority: "normal"
  - github-cli:
      install: true
      priority: "normal"
  - go:
      install: true
      priority: "high"
  - go-yq:
      install: true
      priority: "normal"
  - grub:
      install: true
      priority: "normal"
      themes: true
  - gwenview:
      install: true
      priority: "normal"
  - imagemagick:
      install: true
      priority: "normal"
  - jq:
      install: true
      priority: "high"
  - kcalc:
      install: true
      priority: "normal"
  - kitty:
      install: true
      priority: "normal"
      themes: true
  - konsole:
      install: true
      priority: "normal"
      themes: true
  - kpackage:
      install: true
      priority: "normal"
  - kscreenlocker:
      install: true
      priority: "normal"
  - lazygit:
      install: true
      priority: "normal"
      themes: true
  - less:
      install: true
      priority: "normal"
  - libreoffice-fresh:
      install: true
      priority: "normal"
      themes: true
  - lsof:
      install: true
      priority: "normal"
  - man-db:
      install: true
      priority: "normal"
  - man-pages:
      install: true
      priority: "normal"
  - miniconda:
      install: true
      priority: "normal"
  - mkcert:
      install: true
      priority: "normal"
  - ncdu:
      install: true
      priority: "normal"
  - neovim:
      install: true
      priority: "normal"
  - net-tools:
      install: true
      priority: "normal"
  - nmap:
      install: true
      priority: "normal"
  - nordvpn-bin:
      install: true
      priority: "normal"
      secrets: true
  - nordvpn-gui:
      install: true
      priority: "normal"
  - noto-fonts:
      install: true
      priority: "normal"
  - noto-fonts-cjk:
      install: true
      priority: "normal"
  - noto-fonts-emoji:
      install: true
      priority: "normal"
  - noto-fonts-extra:
      install: true
      priority: "normal"
  - nss:
      install: true
      priority: "normal"
  - ntfs-3g:
      install: true
      priority: "normal"
  - nvm:
      install: true
      priority: "high"
  - nvtop:
      install: true
      priority: "normal"
  - okular:
      install: true
      priority: "normal"
  - onedrive-abraunegg:
      install: true
      priority: "normal"
      secrets: true
  - onedrivegui:
      install: true
      priority: "normal"
  - openssh:
      install: true
      priority: "normal"
      secrets: true
  - pacman:
      install: true
      priority: "high"
  - pacman-contrib:
      install: true
      priority: "normal"
  - papirus-folders:
      install: true
      priority: "normal"
  - papirus-icon-theme:
      install: true
      priority: "normal"
  - partitionmanager:
      install: true
      priority: "normal"
  - perl-image-exiftool:
      install: true
      priority: "normal"
  - pigz:
      install: true
      priority: "normal"
  - plasma-x11-session:
      install: true
      priority: "normal"
  - plocate:
      install: true
      priority: "normal"
  - pnpm:
      install: true
      priority: "normal"
  - postman-bin:
      install: true
      priority: "normal"
  - procs:
      install: true
      priority: "normal"
  - pyenv:
      install: true
      priority: "high"
  - python-pip:
      install: true
      priority: "normal"
  - python-pipx:
      install: true
      priority: "normal"
  - python-poetry:
      install: true
      priority: "normal"
  - python-shtab:
      install: true
      priority: "normal"
  - qbittorrent:
      install: true
      priority: "normal"
      themes: true
  - reflector:
      install: true
      priority: "high"
  - ripgrep:
      install: true
      priority: "normal"
  - rsync:
      install: true
      priority: "normal"
  - rustup:
      install: true
      priority: "high"
  - sddm:
      install: true
      priority: "normal"
      themes: true
  - shellcheck:
      install: true
      priority: "normal"
  - shfmt:
      install: true
      priority: "normal"
  - smplayer:
      install: true
      priority: "normal"
  - starship:
      install: true
      priority: "normal"
      themes: true
  - superfile:
      install: true
      priority: "normal"
      themes: true
  - tdrop:
      install: true
      priority: "normal"
  - thunderbird:
      install: true
      priority: "normal"
  - tk:
      install: true
      priority: "normal"
  - tldr:
      install: true
      priority: "normal"
  - tmux:
      install: true
      priority: "normal"
  - tmuxp:
      install: true
      priority: "normal"
  - unrar:
      install: true
      priority: "normal"
  - unzip:
      install: true
      priority: "normal"
  - usbutils:
      install: true
      priority: "normal"
  - vim:
      install: true
      priority: "normal"
      themes: true
  - virtualbox:
      install: true
      priority: "normal"
  - virtualbox-guest-iso:
      install: true
      priority: "normal"
  - virtualbox-host-dkms:
      install: true
      priority: "normal"
  - visual-studio-code-bin:
      install: true
      priority: "normal"
  - xclip:
      install: true
      priority: "normal"
  - xmlstarlet:
      install: true
      priority: "high"
  - yay:
      install: true
      priority: "highest"
  - zip:
      install: true
      priority: "normal"
  - zoom:
      install: true
      priority: "normal"
  - zoxide:
      install: true
      priority: "normal"
