description: "A maintained, feature-rich and performance oriented, neofetch like system information tool"
label: "fastfetch"
name: "fastfetch"
repository: "extra"
repository_url: "https://archlinux.org/packages/extra/x86_64/fastfetch/"
source_url: "https://github.com/fastfetch-cli/fastfetch/"
url: "https://github.com/fastfetch-cli/fastfetch/"
