description: "KCalc has everything you would expect from a scientific calculator"
label: "KCalc"
name: "kcalc"
repository: "extra"
repository_url: "https://archlinux.org/packages/extra/x86_64/kcalc/"
source_url: "https://invent.kde.org/utilities/kcalc/"
url: "https://apps.kde.org/kcalc/"
