description: "Userspace utilities to manage btrfs filesystems"
label: "BTRFS tools"
name: "btrfs-progs"
optional: ""
repository: "core"
repository_url: "https://archlinux.org/packages/core/x86_64/btrfs-progs/"
source_url: "https://github.com/kdave/btrfs-progs/"
url: "https://btrfs.readthedocs.io/en/latest/"
